# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' param list of genes to organize into a network (<30 genes)
#' param list of cells that are used, (empty list means all cells)
NULL

#' export
NULL

#' Save InferN0 Scope
#'
#' param path file path for the scope to save
#'
#' export
NULL

#' Load InferN0 Scope
#'
#' param path file path to a saved scope
#'
#' export
NULL

InferN0_identifyL0Network <- function(x, y) {
    .Call('_InferN0_InferN0_identifyL0Network', PACKAGE = 'InferN0', x, y)
}

InferN0_identifyL0NetworkGold <- function(x, y, z) {
    .Call('_InferN0_InferN0_identifyL0NetworkGold', PACKAGE = 'InferN0', x, y, z)
}

InferN0_printstringlist <- function(x) {
    .Call('_InferN0_InferN0_printstringlist', PACKAGE = 'InferN0', x)
}

InferN0_identifyL0NetworkGoldResurrected <- function(input, list, traincov, trainmean) {
    .Call('_InferN0_InferN0_identifyL0NetworkGoldResurrected', PACKAGE = 'InferN0', input, list, traincov, trainmean)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_wilcox_geneset <- function(scope, list) {
    .Call('_InferN0_infernal_wilcox_geneset', PACKAGE = 'InferN0', scope, list)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_wilcox_scope <- function(scope, list) {
    .Call('_InferN0_infernal_wilcox_scope', PACKAGE = 'InferN0', scope, list)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_wilcox_matrix <- function(input, list) {
    .Call('_InferN0_infernal_wilcox_matrix', PACKAGE = 'InferN0', input, list)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_find_DE <- function(scope, list) {
    .Call('_InferN0_infernal_find_DE', PACKAGE = 'InferN0', scope, list)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_find_markers <- function(scope, rlist) {
    .Call('_InferN0_infernal_find_markers', PACKAGE = 'InferN0', scope, rlist)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_sharedDE <- function(input) {
    .Call('_InferN0_infernal_sharedDE', PACKAGE = 'InferN0', input)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_cmpInverses <- function(input) {
    .Call('_InferN0_infernal_cmpInverses', PACKAGE = 'InferN0', input)
}

#' Check S4 Class Object
#'
#' @param S4 Class object
#' @param string name of queried slot
#'
#' @export
testSlot <- function(obj, slot) {
    invisible(.Call('_InferN0_testSlot', PACKAGE = 'InferN0', obj, slot))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_serialize <- function(obj) {
    .Call('_InferN0_infernal_serialize', PACKAGE = 'InferN0', obj)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_deserialize <- function(obj, src) {
    invisible(.Call('_InferN0_infernal_deserialize', PACKAGE = 'InferN0', obj, src))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_createScope <- function() {
    .Call('_InferN0_infernal_createScope', PACKAGE = 'InferN0')
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_readScope <- function(path) {
    .Call('_InferN0_infernal_readScope', PACKAGE = 'InferN0', path)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_readScope2 <- function(path) {
    .Call('_InferN0_infernal_readScope2', PACKAGE = 'InferN0', path)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_writeScope <- function(infscope, path) {
    invisible(.Call('_InferN0_infernal_writeScope', PACKAGE = 'InferN0', infscope, path))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_writeScope2 <- function(infscope, serialized, path) {
    invisible(.Call('_InferN0_infernal_writeScope2', PACKAGE = 'InferN0', infscope, serialized, path))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_readMatrixFolder <- function(list) {
    .Call('_InferN0_infernal_readMatrixFolder', PACKAGE = 'InferN0', list)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_convertDenseTextMatrixToSparseFormat <- function(list) {
    invisible(.Call('_InferN0_infernal_convertDenseTextMatrixToSparseFormat', PACKAGE = 'InferN0', list))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_exportDataAsMtx <- function(infscope, list) {
    invisible(.Call('_InferN0_infernal_exportDataAsMtx', PACKAGE = 'InferN0', infscope, list))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_reverseTCM <- function(rscp, list) {
    invisible(.Call('_InferN0_infernal_reverseTCM', PACKAGE = 'InferN0', rscp, list))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_reverseTCM_inMTX <- function(list) {
    invisible(.Call('_InferN0_infernal_reverseTCM_inMTX', PACKAGE = 'InferN0', list))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_readSparseMatrix <- function(scope, x, isRaw) {
    invisible(.Call('_InferN0_infernal_readSparseMatrix', PACKAGE = 'InferN0', scope, x, isRaw))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_readDenseMatrix <- function(scope, x, isRaw) {
    invisible(.Call('_InferN0_infernal_readDenseMatrix', PACKAGE = 'InferN0', scope, x, isRaw))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_createOutput <- function(data) {
    .Call('_InferN0_infernal_createOutput', PACKAGE = 'InferN0', data)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_fitNegativeBinomial <- function(data) {
    .Call('_InferN0_infernal_fitNegativeBinomial', PACKAGE = 'InferN0', data)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_getParameterList <- function(rscp) {
    .Call('_InferN0_infernal_getParameterList', PACKAGE = 'InferN0', rscp)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_setParameter <- function(rscp, which, value) {
    .Call('_InferN0_infernal_setParameter', PACKAGE = 'InferN0', rscp, which, value)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_getParameter <- function(rscp, which) {
    .Call('_InferN0_infernal_getParameter', PACKAGE = 'InferN0', rscp, which)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_getDataRow <- function(rscp, list) {
    .Call('_InferN0_infernal_getDataRow', PACKAGE = 'InferN0', rscp, list)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_runTestFunction <- function(data) {
    invisible(.Call('_InferN0_infernal_runTestFunction', PACKAGE = 'InferN0', data))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_HierarchicalClustering <- function(infscope, list) {
    invisible(.Call('_InferN0_infernal_HierarchicalClustering', PACKAGE = 'InferN0', infscope, list))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_computePartialCorrelation <- function(infscope, list) {
    .Call('_InferN0_infernal_computePartialCorrelation', PACKAGE = 'InferN0', infscope, list)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_IdentifyNetwork <- function(input, list, traincov, trainmean) {
    .Call('_InferN0_infernal_IdentifyNetwork', PACKAGE = 'InferN0', input, list, traincov, trainmean)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_IdentifyConstrainedCovar <- function(input, list, traincov, trainmean) {
    .Call('_InferN0_infernal_IdentifyConstrainedCovar', PACKAGE = 'InferN0', input, list, traincov, trainmean)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_saveHierarchical <- function(data, path) {
    invisible(.Call('_InferN0_infernal_saveHierarchical', PACKAGE = 'InferN0', data, path))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_show <- function(data) {
    invisible(.Call('_InferN0_infernal_show', PACKAGE = 'InferN0', data))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_computeCovar <- function(scptrexp, list) {
    .Call('_InferN0_infernal_computeCovar', PACKAGE = 'InferN0', scptrexp, list)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_getFullDeviations <- function(InferN0scp, list) {
    .Call('_InferN0_infernal_getFullDeviations', PACKAGE = 'InferN0', InferN0scp, list)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_cmpModeledVariance <- function(infscope, list) {
    .Call('_InferN0_infernal_cmpModeledVariance', PACKAGE = 'InferN0', infscope, list)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_cmpVariance <- function(infscope, list) {
    .Call('_InferN0_infernal_cmpVariance', PACKAGE = 'InferN0', infscope, list)
}

#' Internal Function, see R code for documentation instead
#' @export
.internal_Infern0_hierarchicalClustering_CustomGroups <- function(data, cellgroup, nbclusters) {
    .Call('_InferN0_internal_Infern0_hierarchicalClustering', PACKAGE = 'InferN0', data, cellgroup, nbclusters)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_mergeSparseMatrices <- function(matrixA, matrixB) {
    .Call('_InferN0_infernal_mergeSparseMatrices', PACKAGE = 'InferN0', matrixA, matrixB)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_genSynthetic <- function(infscope, data) {
    .Call('_InferN0_infernal_genSynthetic', PACKAGE = 'InferN0', infscope, data)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_initModelWithClustering <- function(infscope, data) {
    invisible(.Call('_InferN0_infernal_initModelWithClustering', PACKAGE = 'InferN0', infscope, data))
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_modelhidden <- function(infscope, data) {
    .Call('_InferN0_infernal_modelhidden', PACKAGE = 'InferN0', infscope, data)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_modelhidden_v2 <- function(infscope, data) {
    .Call('_InferN0_infernal_modelhidden_v2', PACKAGE = 'InferN0', infscope, data)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernal_exportpcs <- function(infscope, rlist) {
    .Call('_InferN0_infernal_exportpcs', PACKAGE = 'InferN0', infscope, rlist)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernalDensity <- function(data, inlist) {
    .Call('_InferN0_infernalDensity', PACKAGE = 'InferN0', data, inlist)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernalTest <- function() {
    .Call('_InferN0_infernalTest', PACKAGE = 'InferN0')
}

#' Internal Function, see R code for documentation instead
#' @export
.infernalKendallCols <- function(x) {
    .Call('_InferN0_infernalKendallCols', PACKAGE = 'InferN0', x)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernalCumulant <- function(inlist) {
    .Call('_InferN0_infernalCumulant', PACKAGE = 'InferN0', inlist)
}

#' Internal Function, see R code for documentation instead
#' @export
.infernalDeconvolve2D <- function(scdata_in, bulk_in, inlist) {
    .Call('_InferN0_infernalDeconvolve2D', PACKAGE = 'InferN0', scdata_in, bulk_in, inlist)
}

